---
name: Fly Deploy (Staging)
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app (staging)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy -c fly.staging.toml --remote-only
          flyctl ssh console -c fly.staging.toml -u user -C 'python manage.py loaddata server/fixtures/sample_data.json'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
