---
name: CI Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Ensure requirements.txt and pyproject.toml in sync
        run: |
          poetry lock --no-update
          poetry export --without-hashes -o requirements.txt
          git diff --exit-code

      - name: Ensure server/templates/index.html is in sync with the frontend
        run: |
          poetry install --no-root --only dev
          poetry run ./scripts/update-index-template
          git diff --exit-code

  build-django-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test
